# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/tbltetmo/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/tbltetmo/proprietary/CSCVersion.txt:system/CSCVersion.txt \
    vendor/samsung/tbltetmo/proprietary/SW_Configuration.xml:system/SW_Configuration.xml \
    vendor/samsung/tbltetmo/proprietary/lib/libremotedesktop_client.so:system/lib/libremotedesktop_client.so \
    vendor/samsung/tbltetmo/proprietary/lib/libremotedesktopservice.so:system/lib/libremotedesktopservice.so \
    vendor/samsung/tbltetmo/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/tbltetmo/proprietary/etc/apns-conf.xml:system/etc/apns-conf.xml \
    vendor/samsung/tbltetmo/proprietary/etc/mixer_paths.xml:system/etc/mixer_paths.xml \
    vendor/samsung/tbltetmo/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/tbltetmo/proprietary/lib/libagc_max.so:system/lib/libagc_max.so \
    vendor/samsung/tbltetmo/proprietary/lib/libqservice.so:system/lib/libqservice.so \
    vendor/samsung/tbltetmo/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/samsung/tbltetmo/proprietary/lib/libqdutils.so:system/lib/libqdutils.so \
    vendor/samsung/tbltetmo/proprietary/lib/libjpegehw.so:system/lib/libjpegehw.so \
    vendor/samsung/tbltetmo/proprietary/lib/libjpegdhw.so:system/lib/libjpegdhw.so \
    vendor/samsung/tbltetmo/proprietary/lib/libedmnativehelper.so:system/lib/libedmnativehelper.so \
    vendor/samsung/tbltetmo/proprietary/lib/libbt-iopdb.so:system/lib/libbt-iopdb.so \
    vendor/samsung/tbltetmo/proprietary/lib/libbt-iopdb_mod.so:system/lib/libbt-iopdb_mod.so \
    vendor/samsung/tbltetmo/proprietary/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/tbltetmo/proprietary/lib/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
    vendor/samsung/tbltetmo/proprietary/lib/libbt-aptX-ARM-4.2.2.so:system/lib/libbt-aptX-ARM-4.2.2.so \
    vendor/samsung/tbltetmo/proprietary/lib/libbt-codec_sshd.so:system/lib/libbt-codec_sshd.so \
    vendor/samsung/tbltetmo/proprietary/lib/libshdace.so:system/lib/libshdace.so \
    vendor/samsung/tbltetmo/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/tbltetmo/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/tbltetmo/proprietary/priv-app/com.qualcomm.location/com.qualcomm.location.apk:system/priv-app/com.qualcomm.location/com.qualcomm.location.apk \
    vendor/samsung/tbltetmo/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/tbltetmo/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/tbltetmo/proprietary/bin/mdm_helper:system/bin/mdm_helper \
    vendor/samsung/tbltetmo/proprietary/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    vendor/samsung/tbltetmo/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/tbltetmo/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/tbltetmo/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/tbltetmo/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/tbltetmo/proprietary/bin/rmnetcli:system/bin/rmnetcli \
    vendor/samsung/tbltetmo/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/tbltetmo/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/tbltetmo/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/samsung/tbltetmo/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/tbltetmo/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/tbltetmo/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/tbltetmo/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so
